--- #YAML:1.0
name:                Socket-Class-SSL
version:             0.99_01
abstract:            SSL support for Socket::Class
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Socket::Class:                 1.9911
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
